Fix uclibc build issue
This patch fixes the following compilation error raised by the bump to
version 1.13.1 in Buildroot [1] using uclibc as the C library for the
cross-compilation toolchain:

net.c: In function 'babel_send':
net.c:199:27: error: 'IPV6_DONTFRAG' undeclared (first use in this function)
  199 |         cmsg->cmsg_type = IPV6_DONTFRAG;;

[1] https://patchwork.ozlabs.org/project/buildroot/patch/20240917201030.11583-1-dario.binacchi@amarulasolutions.com/
Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>